db/urls.py
from django.urls import path
from django.conf.urls import url
from . import views
from .views_ajax import InvestigationGridView

app_name = 'db'

urlpatterns = [
    path('search/', views.search, name='search'),
    path('browse/', views.browse, name='browse'),
    path('upload/', views.upload_view, name='upload'),
    path('confirm/sample/', views.confirm_samples_view, name='confirm_samples'),
    path('add/investigation/', views.add_investigations_view, name='add_investigation'),
    path('search/investigation/', views.investigation_search, name='search_investigation'),
    path('add/sample/', views.add_sample_view, name='add_sample'),
    path('add/wetlab/', views.add_wetlab_view, name='add_wetlab'),
    path('add/biological_protocol/', views.add_biological_protocol_view, name='add_biological_protocol'),
    path('add/pipeline_results/', views.add_pipeline_results_view, name='add_pipeline_results'),
    #Note, I think we need to usue the old URL calls here for DJK
]

metaprovenance/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf.urls import url
from landingpage.views import index
from db.views_ajax import InvestigationGridView, ReplicateFkWidgetGrid, SampleFkWidgetGrid, ProtocolStepFkWidgetGrid
from db.views import (
    InvestigationCreate, InvestigationDetail, InvestigationList,
    InvestigationUpdate, InvestigationMetadataDetail, 
    ProtocolCreate, ProtocolDetail, ProtocolList, ProtocolUpdate,
    ProtocolStepCreate, ProtocolStepDetail,
    ProtocolStepList, ProtocolStepUpdate,
    SampleDetail, SampleList, SampleUpdate
)

urlpatterns = [
    # Main page routing
    path('admin/', admin.site.urls),
    path('account/', include('accounts.urls')),
    path('', index, name='landing'),

    # Investigation Routing
    re_path(r'investigation/all(?P<action>/?\w*)/$', InvestigationList.as_view(), 
            name='investigation_all',
            kwargs={'view_title': 'All Investigations'}),
    re_path(r'investigation/all/$', InvestigationList.as_view(), 
            name='investigation_all',
            kwargs={'view_title': 'All Investigations'}),
    re_path(r'investigation/create/$', InvestigationCreate.as_view(),
        name='investigation_create',
        kwargs={'view_title': "Create New Investigation", 'allow_anonymous': False}),
    re_path(r'investigation/(?P<investigation_id>\d+)/$', InvestigationDetail.as_view(),
        name='investigation_detail',
        kwargs={'view_title': 'All Investigations', 'allow_anonymous': True}),
    re_path(r'investigation/edit/(?P<investigation_id>\d+)/$', InvestigationUpdate.as_view(),
        name='investigation_update',
        kwargs={'view_title': 'Update Investigation', 'allow_anonymous': False}),

    # Sample Routing
    re_path(r'sample/all/$', SampleList.as_view(),
            name = 'sample_all',
            kwargs = {'view_title': 'All Samples', 'allow_anonymous': True}),
    re_path(r'sample/(?P<sample_id>\d+)/$', SampleDetail.as_view(),
        name='sample_detail',
        kwargs={'view_title': 'Sample Detail', 'allow_anonymous': True}),
    re_path(r'sample/edit/(?P<sample_id>\d+)/$', SampleUpdate.as_view(),
        name='sample_update',
        kwargs={'view_title': 'Sample Update', 'allow_anonymous': False}),

    # Investigation Metadata Routing
    re_path(r'investigation/metadata/(?P<investigation_id>\d+)/$', InvestigationMetadataDetail.as_view(),
        name='investigation_metadata_detail',
        kwargs={'view_title': 'Investigation Metadata', 'allow_anonymous': True}),

    # Replicate Routing
    # Replicates are added via the Sample edit page. Should there be replicate
    # specific pages?

    # Protocol Routing
    re_path(r'protocol/(?P<protocol_id>\d+)/$', ProtocolDetail.as_view(),
        name='protocol_detail',
        kwargs={'view_title': "Protocol Detail", 'allow_anonymous': True}),
    re_path(r'protocol/all/$', ProtocolList.as_view(),
        name='protocol_all',
        kwargs={'view_title': "View All Protocols", 'allow_anonymous': True}),
    re_path(r'protocol/create/$', ProtocolCreate.as_view(),
        name = 'protocol_create',
        kwargs={'view_title': "Create New Protocol", 'allow_anonymous': False}),
    re_path(r'protocol/edit/(?P<protocol_id>\d+)/$', ProtocolUpdate.as_view(),
        name = 'protocol_update',
        kwargs={'view_title': "Protocol Update", 'allow_anonymous': False}),

    # Protocol Step Routing
    re_path(r'protocol/step/all/$', ProtocolStepList.as_view(),
            name='protocol_step_all',
            kwargs={'view_title': "View All Protocol Steps", 'allow_anonymous': True}),
    re_path(r'protocol/step/create/$', ProtocolStepCreate.as_view(),
        name = 'protocol_step_create',
        kwargs={'view_title': "Create New Protocol Step", 'allow_anonymous': False}),
    re_path(r'protocol/step/(?P<protocol_step_id>\d+)/$', ProtocolStepDetail.as_view(),
        name = 'protocol_step_detail',
        kwargs={'view_title': "Protocol Step Detail", 'allow_anonymous': True}),
    re_path(r'protocol/step/edit/(?P<protocol_step_id>\d+)/$', ProtocolStepUpdate.as_view(),
        name = 'protocol_step_update',
        kwargs = {'view_title': "Protocol Step Update", 'allow_anonymous': False}),

    # Inline Forim Routing, AJAX FkWidgetGrids, currently unused
    re_path(r'protocol-step-grid(?P<action>/?\w*)/$', ProtocolStepFkWidgetGrid.as_view(),
        name='protocol_step_grid', kwargs={'ajax':True}),
    re_path(r'sample-grid(?P<action>/?\w*)/$', SampleFkWidgetGrid.as_view(),
        name='sample_grid', kwargs={'ajax':True}),
    re_path(r'replicate-grid(?P<action>/?\w*)/$', ReplicateFkWidgetGrid.as_view(),
        name='replicate_grid', kwargs={'ajax':True})
]

js_info_dict = {
            'domain': 'djangojs',
            'packages': ('metaprovenance',),
                }

try:
    from django.views.i18n import JavaScriptCatalog
    urlpatterns += [
        url(r'^jsi18n/$', JavaScriptCatalog.as_view(**js_info_dict), name='javascript-catalog'),
    ]
except ImportError:
    from django.views.i18n import javascript_catalog
    urlpatterns += [
        url(r'^jsi18n/$', javascript_catalog, js_info_dict, name='javascript-catalog',)
    ]

db/views.py
from django.shortcuts import render, redirect
from .forms import UploadTestForm, CreateInvestigationForm, ConfirmSampleForm
from django.shortcuts import render
from django.views import View
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.contrib.messages import get_messages
from django.http import JsonResponse
from django.urls import reverse
from django.utils.html import format_html, mark_safe

from django_jinja_knockout.utils.sdv import call_prop
from django_jinja_knockout.views import (
        BsTabsMixin, ListSortingView, InlineCreateView, InlineCrudView, InlineDetailView
)

import django_tables2 as tables
import io

from metaprovenance.middleware import ContextMiddleware

from .formatters import format_sample_metadata, guess_filetype
from .models import (
        Sample, SampleMetadata, Investigation, BiologicalReplicateProtocol,
        ProtocolStep
)

from .forms import (
    InvestigationDisplayWithInlineSamples, InvestigationWithInlineSamples,
    ProtocolForm, ProtocolDisplayWithInlineSteps, 
    ProtocolStepWithInlineParameters, ProtocolStepDisplayWithInlineParameters,
    ProtocolWithInlineSteps, SampleDisplayWithInlineMetadata,
    SampleWithInlineMetadata
)

import pandas as pd
import numpy as np

'''
DJK INVESTIGATIONS
Class-based Django-Jinja-Knockout views
'''

class InvestigationList(ListSortingView):
    model = Investigation
    allowed_sort_orders = '__all__'
    #allowed_filter_fields = {'description': None}
    grid_fields = ['name', 'institution', 'description']
    list_display = ['edit_investigation']
    def get_heading(self):
        return "Investigation List"
    def edit_investigation(self, obj):
        return format_html(
           '<a href="{}"><span class="iconui iconui-edit"></span></a>',
           reverse('investigation_update', kwargs={'investigation_id': obj.pk}))

    def get_name_links(self, obj):
        links = [format_html(
            '<a href="{}">{}</a>',
            reverse('investigation_detail', kwargs={'investigation_id': obj.pk}),
            obj.name
        )]
        # is_authenticated is not callable in Django 2.0.
        if self.request.user.is_authenticated:
            links.append(format_html(
                ' (<a href="{}"><span class="iconui iconui-edit"></span></a>',
                reverse('investigation_update', kwargs={'investigation_id': obj.pk})
            ))
            links.append(format_html(
                ' <a href="{}"><span class="iconui iconui-file"></span></a>)',
                reverse('investigation_metadata_detail', kwargs={'investigation_id': obj.pk})
            ))
        return links
        
    def get_display_value(self, obj, field):
        if field == 'name':
            links = self.get_name_links(obj)
            return mark_safe(''.join(links))
        else:
            return super().get_display_value(obj, field)

    def get_bs_form_opts(self):
        return {
            'title': "All Investigations",
            'view_title': "All Investigations2",
            'submit_text': "Save Investigation"
        }


class InvestigationDetail(InlineDetailView):
    pk_url_kwarg = 'investigation_id'
    #template_name = 'investigation_edit.htm'
    form_with_inline_formsets = InvestigationDisplayWithInlineSamples

class InvestigationUpdate(BsTabsMixin, InlineCrudView):
    format_view_title = True
    pk_url_kwarg = 'investigation_id'
    form_with_inline_formsets = InvestigationWithInlineSamples
    def get_bs_form_opts(self):
        return {
            'title': format_html('Edit "{}"', self.object),
            'submit_text': 'Save Investigation'
        }

class InvestigationCreate(BsTabsMixin, InlineCreateView):
    format_view_title = True
    pk_url_kwarg = 'investigation_id'
    form_with_inline_formsets = InvestigationWithInlineSamples
    def get_heading(self):
        return "Create New Investigation"
    def get_bs_form_opts(self):
        return {
            'submit_text': 'Save Investigation'
        }

    def get_success_url(self):
        return reverse('investigation_detail', kwargs={'investigation_id': self.object.pk})    

class SampleList(ListSortingView):
    model = Sample
    allowed_sort_orders = '__all__'
    grid_fields = ['name', 'investigation']
    def get_heading(self):
        return "Sample List"
    def get_name_links(self, obj):
        links = [format_html(
            '<a href="{}">{}</a>',
            reverse('sample_detail', kwargs={'sample_id': obj.pk}),
            obj.name
        )]
        # is_authenticated is not callable in Django 2.0.
        if self.request.user.is_authenticated:
            links.append(format_html(
                ' (<a href="{}"><span class="iconui iconui-edit"></span></a>)',
                reverse('sample_update', kwargs={'sample_id': obj.pk})
            ))
        return links

    def get_investigation_links(self, obj):
        links = [format_html(
            '<a href="{}">{}</a>',
             reverse('investigation_detail', kwargs={'investigation_id': obj.investigation.pk}),
             obj.investigation.name
         )]
        return links

    def get_display_value(self, obj, field):
        if field == 'name':
            links = self.get_name_links(obj)
            return mark_safe(''.join(links))
        elif field == 'investigation':
            links = self.get_investigation_links(obj)
            return mark_safe(''.join(links))
        else:
            return super().get_display_value(obj, field)


class SampleDetail(InlineDetailView):
    pk_url_kwarg = 'sample_id'
    form_with_inline_formsets = SampleDisplayWithInlineMetadata

class SampleUpdate(BsTabsMixin, InlineCrudView):
    format_view_title = True
    pk_url_kwarg = 'sample_id'
    form_with_inline_formsets = SampleWithInlineMetadata
    def get_bs_form_opts(self):
        return {
            'submit_text': 'Save Sample'
        }

class InvestigationMetadataDetail(ListSortingView):
    model = SampleMetadata
    allowed_sort_orders = '__all__'
    grid_fields = ['sample__name', 'key', 'value']
    #Override the queryset to return the investigation id requested
    def get_heading(self):
        return "Sample Metadata for Investigation \"%s\"" % (Investigation.objects.get(pk=self.kwargs['investigation_id']).name,)
    def get_queryset(self):
        return SampleMetadata.objects.filter(sample__investigation_id=self.kwargs['investigation_id'])

class ProtocolList(ListSortingView):
    model = BiologicalReplicateProtocol
    allowed_sort_orders = '__all__'
    grid_fields = ['name', 'description', 'citation']
    def get_heading(self):
        return "Protocol List"
    def get_name_links(self, obj):
        links = [format_html(
            '<a href="{}">{}</a>',
            reverse('protocol_detail', kwargs={'protocol_id': obj.pk}),
            obj.name
        )]
        # is_authenticated is not callable in Django 2.0.
        if self.request.user.is_authenticated:
            links.append(format_html(
                ' (<a href="{}"><span class="iconui iconui-edit"></span></a>)',
                reverse('protocol_update', kwargs={'protocol_id': obj.pk})
            ))
        return links

    def get_display_value(self, obj, field):
        if field == 'name':
            links = self.get_name_links(obj)
            return mark_safe(''.join(links))
        else:
            return super().get_display_value(obj, field)


class ProtocolStepList(ListSortingView):
    model = ProtocolStep
    allowed_sort_orders = '__all__'
    grid_fields = ['name', 'method']
    def get_heading(self):
        return "Protocol Step List"
    def get_name_links(self, obj):
        links = [format_html(
            '<a href="{}">{}</a>',
            reverse('protocol_step_detail', kwargs={'protocol_step_id': obj.pk}),
            obj.name
        )]
        # is_authenticated is not callable in Django 2.0.
        if self.request.user.is_authenticated:
            links.append(format_html(
                ' (<a href="{}"><span class="iconui iconui-edit"></span></a>)',
                reverse('protocol_step_update', kwargs={'protocol_step_id': obj.pk})
            ))
        return links

    def get_display_value(self, obj, field):
        if field == 'name':
            links = self.get_name_links(obj)
            return mark_safe(''.join(links))
        else:
            return super().get_display_value(obj, field)



class ProtocolDetail(InlineDetailView):
    pk_url_kwarg = 'protocol_id'
    form_with_inline_formsets = ProtocolDisplayWithInlineSteps

class ProtocolCreate(BsTabsMixin, InlineCreateView):
    format_view_title = True
    pk_url_kwarg = 'protocol_id'
    form_with_inline_formsets = ProtocolWithInlineSteps
    def get_heading(self):
        return "Create New Protocol"
    def get_bs_form_opts(self):
        return {
            'title': 'Create Protocol',
            'submit_text': 'Save Protocol',
            'inline_title': 'Protocol Steps'
        }

    def get_success_url(self):
        return reverse('protocol_detail', kwargs={'protocol_id': self.object.pk})

class ProtocolUpdate(BsTabsMixin, InlineCrudView):
    format_view_title = True
    pk_url_kwarg = 'protocol_id'
    form_with_inline_formsets = ProtocolWithInlineSteps
    def get_bs_form_opts(self):
        return {
            'title': 'Update Protocol',
            'submit_text': 'Save Protocol',
        }

    def get_success_url(self):
        return reverse('protocol_detail', kwargs={'protocol_id': self.object.pk})    


class ProtocolStepDetail(InlineDetailView):
    pk_url_kwarg = 'protocol_step_id'
    form_with_inline_formsets = ProtocolStepDisplayWithInlineParameters

class ProtocolStepCreate(BsTabsMixin, InlineCreateView):
    format_view_title = True
    pk_url_kwarg = 'protocol_step_id'
    form_with_inline_formsets = ProtocolStepWithInlineParameters
    def get_heading(self):
        return "Create New Protocol Step"

db/templates/db/add_biological_protocol.html
bio_protocol

db/templates/db/add_investigation.html
{% extends 'db/base.html' %}

{% block content %}

  <!-- todo. make add investigation form -->

    <div class = "add-investigation-form">
      <form method="POST">{% csrf_token %}
        <p class="form-label"><em>{{ action }}</em></p>
        Investigation Name
        <p>{{ form.name }}</p>
        Institution
        <p>{{ form.institution }}</p>
        Description
        <p>{{ form.description }}</p>
      </ul>
        <div class= "center"><button>ADD INVESTIGATION</button></div>
      </form>
    </div>
  <br>

  <!-- todo list investigations for person to select -->

  <!-- todo add search functionality for investigations. -->
 <!--
  <div class="search-investigations">
    <form method="get" action="{% url 'db:search_investigation' %}">
      <input name="q" value="{{ request.GET.q }}" placeholder="Search for existing Investigations">
      <input type="submit">
    </form>
  </div>
  -->
{% endblock %}

db/templates/db/add_pipeline_results.html
pipeline_results

db/templates/db/add_sample.html
add sample page

db/templates/db/add_wetlab.html
wetlab

db/templates/db/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}Data Upload Testing{% endblock %}</title>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
  </head>
  <body>
    <div class="container">
      {% block content %}
      {% endblock %}
    </div>
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    {% block javascript %}
    {% endblock %}
  </body>
</html>

db/templates/db/browse.html
<p>browse</p>

db/templates/db/confirm_samples.html
{% extends "db/base.html" %}
{% block content %}
<h3>Confirm Samples</h3>
{% if form %}
<form method="post">
{% csrf_token %}
<div class="well">
<table>
       <tr> <th>Confirm Add Sample</th></tr>
{% for sample in form.get_sample_checklist %}
<tr><td>{{ sample.label }}</td><td>{{ sample }}<td/><tr/>
{% endfor %}
</table>
</div>
<button id="confirm_button" name="confirm_button" type="submit" 
        class="btn btn-primary" style="float: right; margin-bottom: 4rem;"/>
        Confirm
</button>
</form>
{% else %}
<p>Nothing to confirm!</p>
{% endif %}
{% endblock %}

db/templates/db/search.html
search

db/templates/db/search_investigation.html
<p>investigation search.</p>

db/templates/db/upload.html
{% extends "db/base.html" %}
{% load render_table from django_tables2 %}
{% load static %}

{% block content %}
  <section id="investigation-choice">
    Choose method:
    <ol>
      <li id="add-investigation-anchor">Add analysis to <a href="#">New Investigation</a></li>
      <li id="search-investigation-anchor">Add analysis to <a href="#">Existing Investigation</a></li>
      <li id="from-sop-anchor">Add analysis <a href="#">From FILE</a></li>
    </ol>
  </section>

{# 1. BUTTON TO TRIGGER THE ACTION #}
<div id="sop-upload">
  <div class="modal fade" id="modal-progress" data-backdrop="static" data-keyboard="false">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h4 class="modal-title">Uploading...</h4>
        </div>
        <div class="modal-body">
          <div class="progress">
            <div class="progress-bar" role="progressbar" style="width: 0%;">0%</div>
          </div>
        </div>
      </div>
    </div>
  </div>

  {# 2. FILE INPUT TO BE USED BY THE PLUG-IN #}
  <div id="drop_zone" class="well text-muted text-center" style="margin-top: 2rem; padding-top: 6rem; padding-bottom: 4rem;">
    <span class="glyphicon glyphicon-arrow-down" style="font-size: 4rem;"></span>
    <h3>Drop File Here to Upload</h3>
  </div>
  <div class="well text-muted" style="padding-top: 4rem; padding-bottom: 4rem;">
    <h3>Data input types</h3>
    <div id="info_pane">
          Metadata mapping file (.csv)<br/>
          Protocol file (.csv)<br/>
          QIIME2 artifact (.qza)<br/>
          QIIME2 visualization (.qzv)<br/>
    </div>
  </div>
</div>
<input id="fileupload" type="file" name="upload_file" multiple
       style="display: none;"
       data-form-data='{"csrfmiddlewaretoken": "{{ csrf_token }}"}'>
<form method="post">
{% csrf_token %}
<button id="confirm_button" name="confirm_button" class="btn btn-primary" style="display: none; float: right;"/>Confirm</button>
</form>
{% endblock %}

{% block javascript %}
  {# JQUERY FILE UPLOAD SCRIPTS #}

  <script src="{% static 'js/jquery.min.js' %}"></script>
  <script src="{% static 'js/jquery.ui.widget.js' %}"></script>
  <script src="{% static 'js/jquery.iframe-transport.js' %}"></script>
  <script src="{% static 'js/jquery.fileupload.js' %}"></script>


  {# PHOTOS PAGE SCRIPTS #}

  <script src="{% static 'js/upload.js' %}"></script>
  <script src="{% static 'js/upload_flow.js' %}"></script>

<div class="container">

<div id="search-investigation">
  <div class="search-investigations">
    <br>
    <form method="get" action="{% url 'db:search_investigation' %}">
      <p>Search for existing investigation by name:</p>
      <input name="q" value="{{ request.GET.q }}" placeholder="Search for existing Investigations">
      <input type="submit">
    </form>
  </div>
</div>
</div>

<div id="add-investigation">
  {% include "db/add_investigation.html" with form=create_investigation_form %}
</div>

{% endblock %}